# Generated by Django 4.2 on 2023-05-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banking", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="date",
            new_name="created",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="constant_symbol",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="information",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="specific_symbol",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="variable_symbol",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
