# Generated by Django 4.2 on 2023-05-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_account_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='Current account', max_length=20),
        ),
    ]
